#!/bin/bash

# Check whether an argument was passed by comparing to an array of arguments.
hasopt() {
    item="$1"; shift
    for i in "$@"; do
        if [[ "$item" == "$i" ]]; then
            return 0
        fi
    done
    return 1
}

set -x
RAY_IMAGE=rayproject/ray:2.7.0
kind delete cluster

if hasopt '-d' "$@"; then
    docker image rm $RAY_IMAGE
fi

if hasopt '-b' "$@"; then
    pushd ../../../..
    docker build --build-arg BUILD_DATE="$(date +%Y-%m-%d:%H:%M:%S)" -t $RAY_IMAGE -f ./python/ray/tests/kuberay/Dockerfile . || exit
    popd || exit
fi

kind create cluster || exit
kind load docker-image $RAY_IMAGE || exit
python setup/setup_kuberay.py
RAY_IMAGE=$RAY_IMAGE python test_autoscaling_e2e.py
